[proxy]
listenPort = ":8096"
main_host_keyword = "video.example.com"
destination = "http://192.168.1.240:8096"
skipCheckTimeout = 30					# seconds


# Backends to ping.
# All down backends with the wolEnable flag set to true
# will get a WoL magic packet
[backends.service]
destination = "http://192.168.1.240:8096"
macAddress = "AA:AA:BB:BB:CC:CC"
broadcastIP = "192.168.1.255"
wolPort = 9
ignoredHosts = []
ignoredPaths = []
wolEnable = false

[backends.dataStorage]
destination = "http://192.168.1.250"
macAddress = "AA:AA:BB:BB:CC:CC"
broadcastIP = "192.168.1.255"
wolPort = 9
ignoredHosts = []
ignoredPaths = ["/Sessions"]
wolEnable = true